### ISSUE TITLE
File not defined in node js

### ISSUE THREAD

**Issue by josieoharrow** [kode-team/image-resize#8]
I am getting an error using this library:

"ImageResize.es.js:201
    } else if (src instanceof File || src instanceof Blob) {
                              ^
ReferenceError: File is not defined"

File is not available for node.js so that makes sense. Is this library supposed to be supported for node.js use?

**Comment by redgoose-dev** [comment]
Thank you for your attention.

This module is designed to resize images in browsers.
It is recommended to use modules such as [sharp](https://github.com/lovell/sharp) in the node.js environment.
